# Generated by Django 3.2.8 on 2021-11-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freespace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='ap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='capacity',
            name='client',
            field=models.IntegerField(default=0),
        ),
    ]
