# Generated by Django 3.2.8 on 2021-10-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aruba', '0002_switches_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='switches',
            name='protduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aruba.brand'),
            preserve_default=False,
        ),
    ]
