# Generated by Django 3.2.8 on 2021-10-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aruba', '0003_auto_20211019_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switches',
            old_name='protduct',
            new_name='product',
        ),
    ]
