# Generated by Django 3.2.8 on 2021-10-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aruba', '0004_rename_protduct_switches_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='switches',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, to='aruba.Participant'),
        ),
    ]
