# Generated by Django 3.2.8 on 2021-10-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aruba', '0006_auto_20211019_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participants',
            new_name='Participant',
        ),
        migrations.RemoveField(
            model_name='switches',
            name='participants',
        ),
        migrations.AddField(
            model_name='switches',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, to='aruba.Participant'),
        ),
    ]
