# Generated by Django 3.2.8 on 2021-10-19 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aruba', '0008_auto_20211019_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='switches',
            name='organizer_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
